# Generated by Django 3.2.5 on 2022-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('pid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
